### ISSUE TITLE
Error in validating transition seals

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-wallet#55] opened 2023-05-14 08:23 UTC
Hi @dr-orlovsky,

I continued the consecutive transfer test and found strange behavior at this [step](https://github.com/BP-WG/bp-core/blob/master/seals/src/txout/witness.rs#L95-L103).

The condition is only valid on the first transfer. In subsequent transfers, the outpoint of the seal is always None, causing the `VerifyError::WitnessNotClosingSeal`. This error occurs because the seal outpoints always None after the first transfer.

For Example, the in the list below, the first `blindseal` causes `VerifyError::WitnessNotClosingSeal`:

```rust
BlindSeal { method: TapretFirst, txid: WitnessTx, vout: Vout(0), blinding: 11375681452054571931 }
BlindSeal { method: TapretFirst, txid: Txid(Txid("1ab6073b14c4232f4fac45b32c71b3fabb5234b2af8eef4aa96f72da38f2bf4d")), vout: Vout(0), blinding: 15229399772929434069 }
```

If we comment the [step](https://github.com/BP-WG/bp-core/blob/master/seals/src/txout/witness.rs#L95-L103), the consignment is validated correctly.

**Comment by crisdut** [comment] 2023-05-26 17:53
Hi @dr-orlovsky,

**Transfer Workflow**

I tested in regtest.

My tests consist of issuing a contract with five amounts and trying to send it to the beneficiary in two parts, 1 per invoice. 

- The transaction `9ab6b9837f9a681ecfbdeb6ec34ba002c42b23c6d43e5dd26fe0a56a726b869e` represents the first invoice paid. 
- The transaction `f7418e133dacad73b0d09f77c3c19cdcd486f2df2d30c1754a6b53c5cb85d909`  represents the second invoice paid.

I generate the second PSBT (transaction) from the change UTXO, using the "change" derivation path **/1/0** + **tweak** (Tapret commitment). Because of this, the prev_out of the `f7418e133dacad73b0d09f77c3c19cdcd486f2df2d30c1754a6b53c5cb85d909` is `9ab6b9837f9a681ecfbdeb6ec34ba002c42b23c6d43e5dd26fe0a56a726b869e`.

**Comment by crisdut** [comment] 2023-06-01 06:26
Hi @dr-orlovsky, 

Some updates:

I think I found the issue with consecutive transfers.

When we create a transfer in RGB, the bundle is add to the consignment file with BlindSeal->Txid set to WitnessTx.

The problem is that if the transition has a change assets, the rgb-wallet does not relate the TxId of the transfer with the BlindSeal of change. So when the user tries to spend this change, the system returns the `VerifyError::WitnessNotClosingSeal` error.

In this case, the bundle should be correctly updated in the transfer creation step. In this way, the acceptance stage would remain only to update the status of the contract.
 
 
 PS: I managed to make a transfer with the change, but I was updating the bundles in the acceptance step and not in the transfer. Tomorrow I will try to do the operations in the transfer step.

**Comment by dr-orlovsky** [comment] 2023-06-01 15:29
Sorry, I am failing to parse what you are saying...

> So when the user tries to spend this change, the system returns the VerifyError::WitnessNotClosingSeal error.

This error is generated not when we are trying to spend the change, but when we verify the spend.

> In this case, the bundle should be correctly updated in the transfer creation step. 

Correctly updated to what?

**Comment by crisdut** [comment] 2023-06-01 17:12
Ok, sure, I will try to clarify.

I believe that the problem related to not being able to make transactions using the change from the previous transaction is related to the lack of information on the bundles.

I will separate my explanation into two parts: On the side of who creates the transaction (aka. owner) and on the beneficiary side.

In the current version of rgb-wallet, when a transaction is create, the beneficiary can use the received asset because in the accept step, we use the secret seal to reveal the content of the bundles.

However, on the owner's side, we cannot use the change from the transaction because when we validate the consignment file, the system returns `VerifyError::WitnessNotClosingSeal`.

Yesterday I added one more step in the accept process, which allowed updating the owner's bundle containing the transaction information performed in L1. I managed to spend the owner's change after that.

But in the case of changing the owner, the bundle update should be in the transfer step itself in [this piece of code](https://github.com/RGB-WG/rgb-wallet/blob/master/src/pay.rs#L278-L282).

Is it clearer now?

**Comment by crisdut** [comment] 2023-06-01 20:54
> Why would the owner have a need to use the output belonging to the receiver?

To update the contract state in stock/inventory.

> Still struggling, especially with this part due to a non-standard terminology:

I updated the content. I hope this help.

> But in the case of changing the owner, the bundle update should be in the transfer step itself in [this piece of code](https://github.com/RGB-WG/rgb-wallet/blob/master/src/pay.rs#L278-L282).

Anyway, I'll try the change I mentioned. I think we can talk better using Rust  😆😆😆😆

**Comment by dr-orlovsky** [comment] 2023-06-02 05:29
The sender should not accept the consignment it creates: it must be a no-op. All the data are already put to the stash when the consignment was created.

**Comment by dr-orlovsky** [comment] 2023-06-11 20:25
Ok, I have finally out figured this out. Highly untrivial bug.

It is caused by the fact that the validator needs to know a witness_txid for each of the inputs of the current state transition - which is different from the witness_txid for the current state transition. The code itself was providing the validator with the current one, not the previous one. This resulted that WitnessVout seals resolving to invalid txid and didn't pass the validation.

Bugfix required changes to both BP Core and RGB Core. Here are the PRs:
- https://github.com/BP-WG/bp-core/pull/43
- https://github.com/RGB-WG/rgb-core/pull/156

**Comment by crisdut** [comment] 2023-06-11 21:14
WOW, really?

I had noticed this difference between the TxID that was provided by the seals, sometimes the witness TxId, sometimes the current Txid.

I thought the problem lay in some bad construction of the transitions in the transfer step.

Unfortunately I didn't have time to dig deeper and find this, but I'm glad you did.

I will test ASAP and update you!

Thanks!

**Comment by dr-orlovsky** [comment] 2023-06-12 00:11
Yes, these multiple txid are really confusing and I was hunting them down for a week.

**Comment by zoedberg** [comment] 2023-06-12 09:57
I've tried to patch the dependencies but I'm encountering the following error: 
```
   Compiling rgb-core v0.10.3 (https://github.com/RGB-WG/rgb-core?branch=fix/seal-vout#2295a90e)
error[E0308]: mismatched types
   --> /home/zoe/.cargo/git/checkouts/rgb-core-545e07908459752c/2295a90/src/validation/validator.rs:374:57
    |
374 |                 let witness = Witness::with(witness_tx, anchor.clone());
    |                               -------------             ^^^^^^^^^^^^^^ expected `Proof`, found `Anchor<MerkleProof>`
    |                               |
    |                               arguments to this function are incorrect
    |
    = note: expected enum `bp::dbc::Proof`
             found struct `bp::dbc::Anchor<MerkleProof>`
note: associated function defined here
   --> /home/zoe/.cargo/git/checkouts/bp-core-448b0ccbc7196e74/1c9b487/seals/src/txout/witness.rs:43:12
    |
43  |     pub fn with<L: mpc::Proof + StrictDumb>(tx: Tx, proof: Proof) -> Witness {
    |            ^^^^

error[E0609]: no field `txid` on type `bp::seals::txout::Witness`
   --> /home/zoe/.cargo/git/checkouts/rgb-core-545e07908459752c/2295a90/src/validation/validator.rs:388:28
    |
388 |         let txid = witness.txid;
    |                            ^^^^ unknown field
    |
    = note: available fields are: `tx`, `proof`

error[E0308]: `else` clause of `let...else` does not diverge
   --> /home/zoe/.cargo/git/checkouts/rgb-core-545e07908459752c/2295a90/src/validation/validator.rs:421:101
    |
421 |               let Some(prev_witness_txid) = self.anchor_index.get(&op).map(|anchor| anchor.txid) else {
    |  _____________________________________________________________________________________________________^
422 | |                 self.status.add_warning(Warning::AnchorNotFound(op));
423 | |             };
    | |_____________^ expected `!`, found `()`
    |
    = note:   expected type `!`
            found unit type `()`
    = help: try adding a diverging expression, such as `return` or `panic!(..)`
    = help: ...or use `match` instead of `let...else`

error[E0277]: the trait bound `Result<BlindSeal<bp::Txid>, bp::seals::txout::blind::TxidMismatch>: TxoSeal` is not satisfied
   --> /home/zoe/.cargo/git/checkouts/rgb-core-545e07908459752c/2295a90/src/validation/validator.rs:435:22
    |
435 |                     .verify_many_seals(&seals, &commitment)
    |                      ^^^^^^^^^^^^^^^^^ the trait `TxoSeal` is not implemented for `Result<BlindSeal<bp::Txid>, bp::seals::txout::blind::TxidMismatch>`
    |
    = help: the following other types implement trait `TxoSeal`:
              BlindSeal<Id>
              ExplicitSeal<Id>
    = note: required for `bp::seals::txout::Witness` to implement `single_use_seals::SealWitness<Result<BlindSeal<bp::Txid>, bp::seals::txout::blind::TxidMismatch>>`

Some errors have detailed explanations: E0277, E0308, E0609.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `rgb-core` due to 4 previous errors
```

**Comment by dr-orlovsky** [comment] 2023-06-12 13:26
@zoedberg it can be I forget to push from the other machine. Will be able to check bit later

**Comment by zoedberg** [comment] 2023-06-13 20:48
@dr-orlovsky I've seen you force pushed the PRs, now code compiles but some send tests that previously worked are now failing with:
```
'anchor index is built from the seal sources so mismatch should be impossible: TxidMismatch { expected: Txid("07cc5fdf6364b01bbaf2cece1721441427a72134fccc48aa395b094c5819be98"), present: Txid("68119b68a8dc155eb3b69fff82c004bb5c72d12a33eb75413628790f5065b76d") }', ~/.cargo/git/checkouts/rgb-core-545e07908459752c/a5001f8/src/validation/validator.rs:424:64
```

**Comment by dr-orlovsky** [comment] 2023-06-14 07:40
@zoedberg I added this exception to see if the logic is invalid. And it seems to be invalid.
It is happening from here:

https://github.com/RGB-WG/rgb-core/pull/156/files#diff-5da346970c7ab1a20e8ab37567dd9b358c668ccfd6dccc2c7e6a187cebdd9c5aR424-R427

Can you provide more details on the failing test?

**Comment by dr-orlovsky** [comment] 2023-06-14 07:44
Ok, I have understood in which assumption I was wrong. Pushed to both repos. Also the footprint of the fix now is minimal. Can you pls check now?

**Comment by zoedberg** [comment] 2023-06-14 09:30
@dr-orlovsky Send tests that stopped working with the last update are now working again. While the send test that I think is related to this issue is still failing.

To add more info, the test does the following:

1. Alice issues an asset and sends it to Bob, which receives it succesfully.
2. Then Bob sends the asset back to Alice, which receives it succesfully.
3. Then Alice tries to transfer the asset back again to Bob, but when Bob validates the consignment it fails with the following validation status:

```
Status{
  unresolved_txids: [
    
  ],
  unmined_terminals: [
    Txid("5744b2f70cfde3258eecec8d1fceb79452f6f92cc9cfeda69938b595de866039")
  ],
  failures: [
    ConfidentialSeal(Opout{
      op: OpId(Array<32>(fa702f90d9495c910938d7882a14f4118ff7f18d8a4b897db80a37cac0a31378)),
      ty: 2000,
      no: 1
    })
  ],
  warnings: [
    AnchorNotFound(OpId(Array<32>(3f6a0505f82d0bd35c7f593b6f2f8a18181d59ed85cb0d2d0a2c1c8abc8658f8))),
    TerminalWitnessNotMined(Txid("5744b2f70cfde3258eecec8d1fceb79452f6f92cc9cfeda69938b595de866039"))
  ],
  info: [
    
  ]
}
```

**Comment by dr-orlovsky** [comment] 2023-06-14 10:06
@zoedberg thank you for checking. It seems the failing test is not related to this issue but instead to https://github.com/RGB-WG/rgb-wallet/issues/56

The problem of this issue was not with a seal being confidential but with seal witness txid validation.

**Comment by dr-orlovsky** [comment] 2023-06-14 11:07
@zoedberg this other problem has to be fixed by https://github.com/RGB-WG/rgb-wallet/pull/63

**Comment by dr-orlovsky** [comment] 2023-06-14 16:04
@nicbus this looks like a different bug from the originally reported in thus issue, isn't it?

I mean can I merge the PR fixing this issue and can you open a new one with this problem? ("Anchor absent in the index")

**Comment by nicbus** [comment] 2023-06-15 08:48
> @nicbus this looks like a different bug from the originally reported in thus issue, isn't it?
> 
> I mean can I merge the PR fixing this issue and can you open a new one with this problem? ("Anchor absent in the index")

I'll open a new issue about the warning, but I'm not sure the `InsufficientState` error is related to this warning.

The reason for this is that I'm seeing the `anchor for operation 9cd...bdb is not found in the index` warning on all `rgb accept` invocations and on all `rgb validate` invocations, except for the call to `validate` during the first trasfer after issuance (but then `rgb accept` shows the warning).

**Comment by dr-orlovsky** [comment] 2023-06-15 11:55
> I'll open a new issue about the warning, but I'm not sure the InsufficientState error is related to this warning.

It could be unrelated, so probably a dedicated issue is desirable. `InsufficientState` means that `rgb` can't coinselect enough inputs to cover the amount from the invoice.

Can you also attach a stash which fails in the test?

**Comment by dr-orlovsky** [comment] 2023-06-15 11:55
@nicbus btw do you confirm that this issue is closed and the bugfix works?

**Comment by nicbus** [comment] 2023-06-16 07:55
> @nicbus btw do you confirm that this issue is closed and the bugfix works?

I confirm I don't see the original validation error `transition 11d...dbf doesn't close seal with the witness transaction ca8...33c` anymore.

**Closed** 2023-06-16 08:07 UTC
Labels: bug
