### ISSUE TITLE
Consecutive Transfers does not work

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-wallet#36] opened 2023-04-19 05:02 UTC
Hi @dr-orlovsky,

I cannot spend a contract received via invoice using Tapret.

**Test Steps**

1. Generate an `issue UTXO`.
2. Generate a `change UTXO`.
3. Issue a new contract.
4. Create an **invoice** with the `change UTXO`.
5. Create a payment (consignment) using the invoice.
6. Validate transfer consignment & accept to the stash.
7. Create a new invoice for `another UTXO`.
8. Creates a payment (consignment) using the **new invoice** (This step doesn't work).

I receive the follow error:

```
[2023-04-19T04:56:14Z TRACE rgb] Command-line arguments: Opts {
        verbose: 4,
        data_dir: "/home/crisdut/.rgb",
        chain: Regtest,
        electrum: Some(
            "localhost:50001",
        ),
        command: Transfer {
            method: TapretFirst,
            psbt_file: "./examples/fungible.psbt",
            invoice: RgbInvoice {
                transport: UnspecifiedMeans,
                contract: Some(
                    ContractId(
                        Array<32>(4b2a7de5140d6e3a58365732f4aa23e54bf31151543b4edb801a9a630517b177),
                    ),
                ),
                iface: TypeName(
                    "RGB20",
                ),
                operation: None,
                assignment: None,
                beneficiary: BlindedSeal(
                    SecretSeal(
                        Array<32>(4eb5c009c18f97da42331739e643488f7a98ad51e6a118543052c553a4881046),
                    ),
                ),
                owned_state: Amount(
                    1,
                ),
                chain: None,
                unknown_query: {},
            },
            out_file: "./examples/fungible.rgbc",
        },
    }
[2023-04-19T04:56:14Z DEBUG rgb::runtime] Using data directory '/home/crisdut/.rgb/regtest'
[2023-04-19T04:56:14Z DEBUG rgb::runtime] Reading stock from '/home/crisdut/.rgb/regtest/stock.dat'
[2023-04-19T04:56:14Z DEBUG rgb::runtime] Reading wallets from '/home/crisdut/.rgb/regtest/wallets.yml'
[2023-04-19T04:56:14Z DEBUG rgb] Executing command: transfer
Error: absent information about bundle for operation be6c957b602995d2e2a34567f094bfe2076a2aacf08a048e134f65e0d064234d.
It may happen due to RGB library bug, or indicate internal inventory inconsistency and compromised inventory data storage.
```

I forced a panic to expose the stacktrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BundleAbsent(OpId(Array<32>(be6c957b602995d2e2a34567f094bfe2076a2aacf08a048e134f65e0d064234d)))', /home/crisdut/projects/contrib/rgb-wallet/std/src/persistence/stock.rs:562:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
8dbdaf3b98b600bb482d05baa9b03fc7e4bda92815602930a21447a9dfa9a9fb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BundleAbsent(OpId(Array<32>(be6c957b602995d2e2a34567f094bfe2076a2aacf08a048e134f65e0d064234d)))', /home/crisdut/projects/contrib/rgb-wallet/std/src/persistence/stock.rs:562:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/result.rs:1112:23
   4: <rgbstd::persistence::stock::Stock as rgbstd::persistence::inventory::Inventory>::transition
             at /home/crisdut/projects/contrib/rgb-wallet/std/src/persistence/stock.rs:559:43
   5: rgbstd::persistence::inventory::Inventory::consign
             at /home/crisdut/projects/contrib/rgb-wallet/std/src/persistence/inventory.rs:473:30
   6: rgbstd::persistence::inventory::Inventory::transfer
             at /home/crisdut/projects/contrib/rgb-wallet/std/src/persistence/inventory.rs:401:31
   7: rgbwallet::pay::InventoryWallet::pay
             at /home/crisdut/projects/contrib/rgb-wallet/src/pay.rs:269:24
   8: rgb::command::Command::exec
             at ./src/bin/rgb/command.rs:530:32
   9: rgb::run
             at ./src/bin/rgb/main.rs:78:5
  10: rgb::main
             at ./src/bin/rgb/main.rs:58:23
  11: core::ops::function::FnOnce::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Also, my wallet:

```
outpoint=73c47d24fb79865b9f11274bf5ceab2e087fa9d4dfd2f1dbc6e93b76f06ad6a3:1, height=501, amount=1000000, derivation=*/0/19
outpoint=ee22babca7a06ec3631969af81bd0923b92c42c73c7f4a1d8f84043eead457bb:0, height=502, amount=100000, derivation=*/1/19
```

And contract state:

```
Global:
  Nominal := (ticker=("RGB1"), name=("RGB1"), details=~, precision=8)
  ContractText := ("RGB1.
")

Owned:
  Assets:
    amount=2, utxo=73c47d24fb79865b9f11274bf5ceab2e087fa9d4dfd2f1dbc6e93b76f06ad6a3:1, witness=d0ffcf8edc5a7cfca78a2de3141ca980539bad07d26af39b01d1e6f5329bc1db # owner unknown
    amount=8, utxo=d0ffcf8edc5a7cfca78a2de3141ca980539bad07d26af39b01d1e6f5329bc1db:0, witness=d0ffcf8edc5a7cfca78a2de3141ca980539bad07d26af39b01d1e6f5329bc1db # owner unknown
```

If you need more information, just tell me. 

Thanks!

**Comment by nicbus** [comment] 2023-04-20 09:20
Facing the same issue with opret closing method.

The steps to reproduce are the same.

Looking into the issue I also noticed that:
- the `id` (`OpId`) passed by `consign` is a `Transition` `Input` `Opout`
  `OpId`, while the `opid` received by functions `transition` and
  `anchored_bundle` is used for a lookup on the `Stock`'s `bundle_op_index`,
  which is an index of `TransitionBundle` `OpId`s (maintained by
  `index_bundle`)
- during the first transfer, the `Input` `Opout` that appears in the transition
  is the contract ID and the `id` passed by `consign` corresponds to the
  `TransitionBundle` `OpId`, while during the second transfer the `Input`
  `Opout` and the `id` passed by `consign` match (but the function looks for a
  `TransitionBundle` `OpId`)
- for the sake of understanding what's going on, I tried to modify `transition`
  and `anchored_bundle` functions to use either a `TransitionBundle` or an
  `Input` `Ouput` and got an infinite loop, as the `consign` function extends
  the `id` vector it's looping over with the new transition's input IDs but
  AFAIU for the 2nd transfer that's the same ID that's just been processed

On a related note, also tried to spend a change allocation created with
`WitnessTx` and that also fails, while the recipient is accepting the transfer,
with the following error:
```
Consignment is NOT valid
Validation failures:
- transition f4b656ad1c69694a64fc2078aee22cb58c3fc90df1f484272fa800b634f67778 doesn't close seal with the witness transaction 14fd45afd9e103009e3e80d34b93bc451e21e54767ba75ee2fd5fa934c9cb997. Details: the provided witness transaction 14fd45afd9e103009e3e80d34b93bc451e21e54767ba75ee2fd5fa934c9cb997 does not closes seal 14fd45afd9e103009e3e80d34b93bc451e21e54767ba75ee2fd5fa934c9cb997:1.
Validation warnings:
- duplicated terminal seal CTYj93CakcBAi1eazdoMSpfH2ZbnWTu1pXkcz2SDQQbe in operation f4b656ad1c69694a64fc2078aee22cb58c3fc90df1f484272fa800b634f67778.
```
Not sure the two issues are directly related (haven't looked into the change
one deep enough) but I think it makes sense to take both into consideration, so
that's why I'm adding this info.

Hope these details might help resolve the issue.

**Comment by crisdut** [comment] 2023-04-25 07:59
Hi @dr-orlovsky and @nicbus,

I made new tests and understood the bug, but I'm not sure how we can fix.

When we reveal assignments values, the `OpId` related to the consignment transition is changed. The new `OpId` will be used as prev_out of the new transition, but the `Bundle` related is stored with the original `OpId` provided by the consignment file. 

The error occurs because the `op-to-bundle`  index cannot be updated correctly after the `accept consignment` operation.


I tried to adjust the indexes, but ended up with some errors with mpc_proof.

Hope this helps.

**Comment by dr-orlovsky** [comment] 2023-04-28 10:10
> When we reveal assignments values, the OpId related to the consignment transition is changed. The new OpId will be used as prev_out of the new transition, but the Bundle related is stored with the original OpId provided by the consignment file.

If this is the case, than the `OpId` value in RGB Core is calculated in incorrect way. We had that issue back in the days in old versions (like v0.4 or something). `OpId` must be a commitment to the concealed data and must not change ever.

Checking that in RGB Core...

**Comment by dr-orlovsky** [comment] 2023-04-28 10:35
This should solve the issue: https://github.com/RGB-WG/rgb-core/pull/153

It appeared that the concealed procedure was not completed in RGB Core.

**Comment by dr-orlovsky** [comment] 2023-05-02 08:50
Ok, so the epic to fix this issue includes the following PRs:
- https://github.com/LNP-BP/client_side_validation/pull/121
- https://github.com/BP-WG/bp-core/pull/40
- https://github.com/RGB-WG/rgb-core/pull/153
- https://github.com/RGB-WG/rgb-wallet/pull/45
- https://github.com/RGB-WG/rgb/pull/13

In order to test the full stack of the changes please add to your project `Cargo.toml`:
```toml

[patch.crates-io]
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "commit_encode_derive" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-primitives = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "fix/op-conceal" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "rgb20" }
rgb-wallet = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "rgb20" }
rgb-contracts = { git = "https://github.com/RGB-WG/rgb", branch = "fix/conseq-transfers" }
```

Once @crisdut will re-confirm that all these fixes taken together with the latest commits work - and @zoedberg / @nicbus also check that for their setup - I will merge all of PRs and do a v0.10.1 release yanking old v0.10.0 version (there are consensus-breaking changes due to the new operation commitment construction solving the consecutive transfer issue).

CC @fedsten

**Comment by nicbus** [comment] 2023-05-03 11:43
I repeated the same tests with patched crates as instructed, using `rgbsc` commit `75fa355`, and these are my results:
- spending received assets now works
    - test steps:
        - issue + send: ok
        - send received assets from 1st recipient to a 2nd recipient: ok
- spending assets received back fails
    - test steps:
        - issue + send: ok
        - send received assets from 1st recipient back to issuer: ok
        - send received assets from issuer to a 2nd recipient: fails
    - last transfer fails consignment validation:
        ```
        Consignment is NOT valid
        Non-mined terminals:
        - aeb3d066d15f6add8c44caa9e40e4b2e42d3982e08c966794342e805589b9d9c
        Validation failures:
        - seal c9487efe209648b75d76544b5942b42a790ed1f7ed16a3eb51b49aa0a13f4d79/0/0 present in the history is confidential and can't be validated.
        Validation warnings:
        - terminal witness transaction aeb3d066d15f6add8c44caa9e40e4b2e42d3982e08c966794342e805589b9d9c is not yet mined.
        ```
- spending change creating no further change fails:
    - test steps:
        - issue + send, creating a change allocation (WitnessTx): ok
        - send full change allocation from issuer to a 2nd recipient: fails
    - consignment validates:
        ```
        Consignment has non-mined terminal(s)
        Non-mined terminals:
        - ca85433cc9f2790ca6034cb9f404471cbd781fe374474f9aff8d0d819c97033c
        Validation warnings:
        - terminal witness transaction ca85433cc9f2790ca6034cb9f404471cbd781fe374474f9aff8d0d819c97033c is not yet mined.
        ```
        but accept fails:
        ```
        Consignment is NOT valid
        Validation failures:
        - transition 11d1f8e8d78d9f5040ba94de42499f9f8e94462251589cf6054eeafa50401dbf doesn't close seal with the witness transaction ca85433cc9f2790ca6034cb9f404471cbd781fe374474f9aff8d0d819c97033c. Details: the provided witness transaction ca85433cc9f2790ca6034cb9f404471cbd781fe374474f9aff8d0d819c97033c does not closes seal ca85433cc9f2790ca6034cb9f404471cbd781fe374474f9aff8d0d819c97033c:0.
        ```
- spending change creating a new change fails, with the addition of the "duplicated terminal seal" warning:
    - test steps:
        - issue + send, creating a change allocation (WitnessTx): ok
        - send part of the change allocation from issuer to a 2nd recipient: fails
    - consignment validates:
        ```
        Consignment has non-mined terminal(s)
        Non-mined terminals:
        - f0fcbb74a9f0572658c69ddcc0a7fc11e23e0cea8fbaf898fcccdff2a539372e
        Validation warnings:
        - duplicated terminal seal 51Fzqi8mBuCHXifp95SEtJfFuUtsMa9KqFxv9Bm8i8uG in operation ec79995dd01b684f24119a636253d8e43fdae58f6173cf3e41f807f0ac5e1a88.
        - terminal witness transaction f0fcbb74a9f0572658c69ddcc0a7fc11e23e0cea8fbaf898fcccdff2a539372e is not yet mined.
        ```
        but accept fails:
        ```
        Consignment is NOT valid
        Validation failures:
        - transition ec79995dd01b684f24119a636253d8e43fdae58f6173cf3e41f807f0ac5e1a88 doesn't close seal with the witness transaction f0fcbb74a9f0572658c69ddcc0a7fc11e23e0cea8fbaf898fcccdff2a539372e. Details: the provided witness transaction f0fcbb74a9f0572658c69ddcc0a7fc11e23e0cea8fbaf898fcccdff2a539372e does not closes seal f0fcbb74a9f0572658c69ddcc0a7fc11e23e0cea8fbaf898fcccdff2a539372e:1.
        ```

**Comment by crisdut** [comment] 2023-05-03 11:58
Hi @nicbus,

> * spending assets received back fails

This behavior only happened to me when I tried to make a "self-payment", that is, when I generated the invoice and the transfer pointed to the same stock/inventory.

Have you tried doing this operation with different stocks? (one from the payer and one from the beneficiary)

**Comment by nicbus** [comment] 2023-05-03 12:26
Hi @crisdut, thanks for checking my findings.

> This behavior only happened to me when I tried to make a "self-payment", that is, when I generated the invoice and the transfer pointed to the same stock/inventory.
> 
> Have you tried doing this operation with different stocks? (one from the payer and one from the beneficiary)

I am avoiding self-payments entirely, sender and receiver wallet/stock are always different.

What I meant by "send received assets from issuer to a 2nd recipient", while describing the failing step, is that the original issuer, after receiving back the assets, is trying to send them to another recipient. Specifically, I used a different recipient for the first transfer (issuer -> 1st recipient) and the failing one (issuer -> 2nd recipient) just to be sure there could be no issue due to the recipient being the same.

**Comment by dr-orlovsky** [comment] 2023-05-03 13:05
It seems that failures reported by @nicbus are new issues unrelated to the current one and the stuff in PR. I propose to merge the PRs - but do not perform a release and work on the next set of PRs to fix this issues separately/independently.

**Comment by dr-orlovsky** [comment] 2023-05-11 18:21
All PRs are merged, crates released. Closing this

**Closed by dr-orlovsky** 2023-05-11 18:21 UTC
Labels: bug, epic
